# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,1
monitor=eDP-1,disable

$configs = $HOME/.config/hypr/configs
$scripts = $HOME/.config/hypr/scripts

# Source integral files
source = $configs/ENVariables.conf
source = $configs/Execs.conf
source = $configs/Settings.conf
source = $configs/WindowRules.conf
source = $configs/KeyBindings.conf



