# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,1
monitor=eDP-1,disable

$configs = $HOME/.config/hypr/configs
$scripts = $HOME/.config/hypr/scripts

# Source files
source=$configs/ENVariables.conf
source=$configs/Execs.conf
source=$configs/Settings.conf
source=$configs/WindowRules.conf
source=$configs/KeyBindings.conf
# Redshift for eye protection
source = $scripts/Sunset.sh

#source=$config/hypr/waybar


# Execute your favorite apps at launch
# exec-once = waybar
# exec = nm-applet

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf


