#### SET WINDOW RULES ##################

# Example windowrule v1
windowrule = float, ^(alacritty)$
# Example windowrule v2
windowrulev2 = float,class:^(alacritty)$,title:^(alacritty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = float, ^(pavucontrol)$
windowrule = animation popin,^(pavucontrol)$